name: CI/CD Pipeline 
 
on: [push] 
 
jobs: 
  test: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Récupérer le code 
        uses: actions/checkout@v3 
 
      - name: Installer Python 
        uses: actions/setup-python@v4 
        with: 
          python-version: 3.x 
 
      - name: Installer les dépendances 
        run: pip install -r requirements.txt 
 
      - name: Exécuter les tests 
        run: python -m unittest test_app.py 
  security:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Installer SonarScanner
        run: | 
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner.zip
          echo "$PWD/sonar-scanner-5.0.1.3006-linux/bin" >> $GITHUB_PATH
 
      - name: Analyse du code avec SonarQube
        run: |
          sonar-scanner \
          -Dsonar.organization=peguyannick \
          -Dsonar.projectKey=peguyannick_tp-ci-cd \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.token=${{secrets.SONAR_TOKEN}}
  deploy: 
    needs: test 
    runs-on: ubuntu-latest 
    steps: 
      - name: Déclencher le déploiement sur Render 
        run: | 
          curl -X POST "https://tp-ci-cd-5jbj.onrender.com"